[package]
version = "0.1.0"
name = "test-data-utils"
edition = "2021"

[dependencies]
bitcoin = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }
once_cell = { workspace = true }