[package]
name = "sol-utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
exclude.workspace = true

[[bin]]
name = "sol-utils"
path = "src/main.rs"

[dependencies]
rift-sdk = { workspace = true }
bitcoin-light-client-core = { workspace = true }
checkpoint-downloader = { workspace = true }
sol-bindings= { workspace = true }

hex.workspace = true
alloy = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
