[package]
name = "market-maker"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true
exclude.workspace = true

[[bin]]
name = "market-maker"
path = "src/bin/main.rs"

[dependencies]
rift-sdk = { workspace = true }
bitcoin-light-client-core = { workspace = true }
bitcoin = { workspace = true }
data-engine = { workspace = true }
bitcoin-data-engine = { workspace = true }
rift-core = { workspace = true }
sol-bindings= { workspace = true }
bitcoincore-rpc-async = { workspace = true }
checkpoint-downloader = { workspace = true }
tiny-keccak = { workspace = true }

reqwest = { workspace = true }
tokio-util = { workspace = true, features = ["time"] }
tokio = { workspace = true, features = ["full"] }
tokio-rusqlite = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
eyre = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
alloy = { workspace = true }
backoff = { workspace = true, features = ["tokio"] }
chrono = { workspace = true }
dashmap = "6.1.0"
alloy-primitives = "1.1.0"
alloy-sol-types = "1.1.0"
anyhow = "1.0.98"
log = { workspace = true }
async-trait = "0.1.88"
esplora-client = { workspace = true }
base64 = "0.22.1"
ring = "0.17.14"
jsonwebtoken = "9.3"