[package]
name = "data-engine-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
exclude.workspace = true

[[bin]]
name = "data-engine-server"
path = "src/bin/main.rs"

[dependencies]
bitcoin-light-client-core.workspace = true
checkpoint-downloader.workspace = true

axum.workspace = true
alloy.workspace = true
data-engine.workspace = true
tokio-util.workspace = true
tokio-rusqlite.workspace = true
tokio.workspace = true
eyre.workspace = true
serde.workspace = true
serde_json.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
rift-sdk.workspace = true
tower-http = { version = "0.6.2", features = ["cors"] }
regex = "1.11.1"