[package]
name = "rift-indexer-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
exclude.workspace = true

[[bin]]
name = "rift-indexer-server"
path = "src/bin/main.rs"

[dependencies]
bitcoin-light-client-core.workspace = true
checkpoint-downloader.workspace = true

axum.workspace = true
alloy.workspace = true
rift-indexer.workspace = true
tokio.workspace = true
eyre.workspace = true
serde.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
rift-sdk.workspace = true
tower-http = { workspace = true }
regex = { workspace = true }