[package]
name = "rift-core"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin-light-client-core = { workspace = true }
alloy-sol-types= { workspace = true }
serde = { workspace = true }
bitcoin = { workspace = true }
bitcoin-core-rs = { workspace = true }
tiny-keccak = { workspace = true }
sol-bindings= { workspace = true }
[dev-dependencies]
alloy = { workspace = true }
test-data-utils = { workspace = true }