[package]
name = "test-utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
exclude.workspace = true

[[bin]]
name = "test-utils"
path = "src/main.rs"

[dependencies]
rift-core = { workspace = true }
rift-sdk = { workspace = true }
bitcoin-light-client-core = { workspace = true }

accumulators.workspace = true
hex.workspace = true
alloy = { workspace = true }
clap = { workspace = true }
bitcoin = { workspace = true }
eyre = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
