[package]
version = "0.1.0"
name = "btc-light-client-script"
edition = "2021"
default-run = "benchmark"

[[bin]]
name = "benchmark"
path = "src/bin/benchmark.rs"

[dependencies]
bitcoin-light-client-core = { workspace = true }
bitcoin-core-rs = { workspace = true }
rift-core = { workspace = true }
test-data-utils = { workspace = true }
rift-sdk = { workspace = true }


tokio = { workspace = true }
sp1-sdk = { workspace = true }
clap = { workspace = true }
accumulators = { workspace = true }
prettytable = { workspace = true }

[build-dependencies]
sp1-helper = { workspace = true }
