[package]
name = "hypernode"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hypernode"
path = "src/bin/main.rs"

[dependencies]
sol-bindings= { workspace = true }
bitcoin-light-client-core = { workspace = true }
bitcoin-data-engine = { workspace = true }
rift-core = { workspace = true }
rift-sdk = { workspace = true }
rift-indexer = { workspace = true }
checkpoint-downloader = { workspace = true }
bitcoincore-rpc-async = { workspace = true }
accumulators = { workspace = true }

tokio = { workspace = true }
alloy = { workspace = true }
eyre = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
bitcoin = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
backoff.workspace = true
thiserror.workspace = true
itertools = { workspace = true }
