[package]
version = "0.1.0"
name = "rift-program"
edition = "2021"

[dependencies]
rift-core = { workspace = true }
bitcoin-light-client-core = { workspace = true }
alloy-sol-types = { workspace = true }
sp1-zkvm = { workspace = true }