[package]
name = "data-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
exclude.workspace = true

[[bin]]
name = "contract-indexer"
path = "src/bin/devnet.rs"

[dependencies]
rift-sdk.workspace = true
tokio.workspace = true
eyre.workspace = true
futures-util.workspace = true
alloy.workspace = true
clap.workspace = true
backoff.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
sqlx.workspace = true
serde.workspace = true
serde_json.workspace = true
