name: Build and Push DevNet Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-24.04-amd64-16-cores
          # - arch: arm64
          # runner: ubuntu-24.04-arm64-16-cores

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.devnet
          push: true
          tags: |
            riftresearch/devnet:latest
            riftresearch/devnet:${{ github.sha }}

